### ISSUE TITLE
Handling ISO values

### ISSUE THREAD

**Issue by willow-ahrens** [GraphBLAS/binsparse-specification#26]
In response to our discussion around ISO values today, I'll point people to my draft 2.0 spec: https://github.com/GraphBLAS/binsparse-specification/pull/20. I think either option is easy for me to parse, but option 2 is a closer match to a level-by-level format spec, so I thought I'd ask what y'all think:

Two main options were discussed today:
1. Keep the iso value as part of the datatype (i.e. "iso[int8]"). V1.0 is unchanged. V2.0 needs a change so that the [Element Level](https://github.com/GraphBLAS/binsparse-specification/blob/3a787f6473ecdd894af159bd34bf1f49877c822b/spec/latest/index.bs#L273) will absorb the functionality of the [ISO Level](https://github.com/GraphBLAS/binsparse-specification/blob/3a787f6473ecdd894af159bd34bf1f49877c822b/spec/latest/index.bs#L324).
2. Handle things in the formats (i.e. "iso[CSR]"). The 2.0 PR is unchanged, but V1.0 needs a change so that the predefined formats (like "CSR" or "COO") can also accept "iso[CSR]" or "iso[COO]", and "iso" is no longer part of the datatype.

In option 1, we would add text to the description of an `ElementLevel` to say that 

```
If the values_type is `iso`, then the values array is instead to be interpreted as follows:

: values
:: Array of size `1` whose element holds the value of all explicit entries in the sparse tensor.
```

In option 2, as long as we're in the business of defining format aliases, we would also say that "CSR" is an alias for 
```
{
  "format": {
    "level": "dense",
    "rank": "1",
    "subformat": {
      "level": "sparse",
      "rank": "1",
      "subformat": {
        "level": "element",
      }
    }
  },
}
```

and "iso[CSR]" is an alias for 
```
{
  "format": {
    "level": "dense",
    "rank": "1",
    "subformat": {
      "level": "sparse",
      "rank": "1",
      "subformat": {
        "level": "iso",
      }
    }
  },
}
```

I really think either is fine here, so a simple poll:
❤️ react for 1, 🚀 react for 2

**Comment by eriknw** [comment]
A third option is to not have it encoded in the datatype (i.e., not `"iso[int8]"`) or the format (i.e., not `"iso[CSR]"`), and instead have e.g. `CSR` as the format, `int8` as the datatype, and introduce a new metadata key such as `"is_iso": true`.
