### ISSUE TITLE
Readable version of the html docs?

### ISSUE THREAD

**Issue by rgommers** [GraphBLAS/binsparse-specification#46]
It looks like there is no deployed version of the rendered docs - if there is, I missed it on the front page, everything seems to point to https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/GraphBLAS/binsparse-specification/main/spec/latest/index.bs. That renderer is not only a little confusing, but it shows only a handful of lines of content at a time while taking up most of the window with debug/regenerate panels that cannot be minimized:

<img width="1006" alt="image" src="https://github.com/GraphBLAS/binsparse-specification/assets/98330/05caa9a8-1790-407e-bd4b-c1258b93bf2e">

**Comment by willow-ahrens** [comment]
This should be fixed now, can everyone see the new website? https://graphblas.org/binsparse-specification/

**Comment by BenBrock** [comment]
Looks perfect to me!

**Comment by rgommers** [comment]
Looks great, thanks for the quick fix @willow-ahrens!
